name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: matcha_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 5. Configure environment variables for tests
      - name: Set environment variables
        run: echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/matcha_test" >> $GITHUB_ENV

      # 6. Initialize database schema
      - name: Initialize database schema
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d matcha_test -f ./db/schema.sql

      # 7. Run tests
      - name: Run tests
        run: NODE_ENV=test pnpm test
