name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: matcha_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Debug: Verify files and directories
      - name: "Debug: Verify files"
        run: ls -R

      # 3. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm@latest

      # 4. Debug: Verify pnpm version
      - name: "Debug: Check pnpm version"
        run: pnpm --version

      # 5. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 6. Debug: Verify package.json
      - name: "Debug: Verify package.json"
        run: cat package.json

      # 7. Debug: List available scripts
      - name: "Debug: List available scripts"
        run: pnpm run

      # 8. Set environment variables
      - name: Set environment variables
        run: echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/matcha_test" >> $GITHUB_ENV

      # 9. Initialize database schema
      - name: Initialize database schema
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d matcha_test -f ./db/schema.sql

      # 10. Debug: Run test script
      - name: "Debug: Run tests"
        run: pnpm run test || echo "Script test failed"

      # 11. Run tests
      - name: Run tests
        run: NODE_ENV=test pnpm test
